### ISSUE TITLE
Checklist do report

### ISSUE THREAD

**Issue by philsf** [philsf-biostat/SAR-2021-011-JG#6]
- [ ] Title
- [ ] Objective
- [ ] Data & Methods (from SAP)
- [ ] Conclusions match the results
- [ ] remove watermark
- [ ] update TOC
- [ ] render private + public version
- [ ] update README status + links
